### ISSUE TITLE
The crawl dashboard is not coming up

### ISSUE THREAD

**Issue by rduerr** [memex-explorer/sce#41]
I get the following when I try to bring the crawl dashboard up:

<img width="934" alt="screen shot 2019-03-05 at 10 39 41 pm" src="https://user-images.githubusercontent.com/1544892/53858490-aad1d280-3f97-11e9-8e4d-1099b624d3be.png">
 
I get the same screen when I go to http://0.0.0.0:8983/solr/#/ I get that same error.  Ditto with http://0.0.0.0:8983/banana/.

However, when I check the docker images, they look fine (though there are extras given the testing I was doing a while ago):

<img width="736" alt="screen shot 2019-03-05 at 10 47 07 pm" src="https://user-images.githubusercontent.com/1544892/53858800-b40f6f00-3f98-11e9-8bc8-20c4e0ba5b0e.png">

and the containers seem to be fine as well:

<img width="1389" alt="screen shot 2019-03-05 at 10 48 57 pm" src="https://user-images.githubusercontent.com/1544892/53858843-e1f4b380-3f98-11e9-8cfa-5513770c1b85.png">

but the logs do show that there is a problem - the sce.log repeats the following error every second or two:

2019-03-06 05:36:47 WARN  NativeCodeLoader:62 [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-03-06 05:36:49 INFO  Crawler$:147 [main] - Committing crawldb..
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at edu.usc.irds.sparkler.Main$.main(Main.scala:49)
	at edu.usc.irds.sparkler.Main.main(Main.scala)
Caused by: org.apache.solr.client.solrj.SolrServerException: Server refused connection at: http://localhost:8983/solr/crawldb
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:617)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:484)
	at org.apache.solr.client.solrj.SolrClient.commit(SolrClient.java:463)
	at edu.usc.irds.sparkler.service.SolrProxy.commitCrawlDb(SolrProxy.scala:62)
	at edu.usc.irds.sparkler.pipeline.Crawler.run(Crawler.scala:148)
	at edu.usc.irds.sparkler.base.CliTool$class.run(CliTool.scala:34)
	at edu.usc.irds.sparkler.pipeline.Crawler.run(Crawler.scala:48)
	at edu.usc.irds.sparkler.pipeline.Crawler$.main(Crawler.scala:310)
	at edu.usc.irds.sparkler.pipeline.Crawler.main(Crawler.scala)
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at shaded.org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at shaded.org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at shaded.org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at shaded.org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at shaded.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at shaded.org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:515)
	... 17 more

It looks like Solr is not up and running or at least neither I nor the SCE can connect to it.

Suggestions?

**Comment by buggtb** [comment]
Hey @rduerr ,

I just cloned the repo and installed it locally on my Mac for the first time. It came up alright, although Solr doesn't have an index, that aside it did all start so I'm not getting the error you see.

If you do still see it, can you do:

docker logs compose_sparkler_1

and see if there's anything solr related in it.

**Comment by rduerr** [comment]
@buggtb. I don't know if you saw this response from like 9 days ago....  So am editing to add your handle here....  I would reassign it back to you; but I don't have that permission (annoying as all get out!!!)
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I need to turn the system off - as the logs are still emitting errors every second or two.  However I saved a minute or so from the beginning of the log and grep -i for solr which had lots of perfectly fine looking lines - see attached file...

[headsolrquery.txt](https://github.com/nasa-jpl-memex/sce/files/2947907/headsolrquery.txt)

but the end of the file is just continual "Server refused connection" errors (see attached file)

[tailsolrquery.txt](https://github.com/nasa-jpl-memex/sce/files/2947908/tailsolrquery.txt)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I also note that the file was big enough that github wouldn't create a gist for it... Got an error there too!  So if there is some fragment of the file you'd like to see in particular let me know.

**Comment by rduerr** [comment]
Did a pull and now the crawl appears to be working...
